### ISSUE TITLE
Cannot find module "istanbul" error since mochify-istanbul@2.2.0

### ISSUE THREAD

**Issue by tjunghans** [ferlores/mochify-istanbul#15]
The release 2.2.0 causes the error below (Windows and Unix). Version 2.1.3 works fine.

```
C:\dev\projects\XXX\node_modules\mochify-istanbul\node_modules\resolve\lib\sync.js:33
    throw new Error("Cannot find module '" + x + "' from '" + y + "'");
          ^
Error: Cannot find module 'istanbul' from 'C:\dev\projects\XXX'
    at Function.module.exports [as sync] (C:\dev\projects\XXX\node_modules\mochify-istanbul\node_modules\resolve\lib\sync.js:33:11)
    at instrument (C:\dev\projects\XXX\node_modules\mochify-istanbul\index.js:9:38)
    at module.exports (C:\dev\projects\XXX\node_modules\mochify-istanbul\index.js:100:15)
    at Browserify.plugin (C:\dev\projects\XXX\node_modules\mochify\node_modules\browserify\index.js:347:9)
    at C:\dev\projects\XXX\node_modules\mochify\lib\mochify.js:136:11
    at Array.forEach (native)
    at module.exports (C:\dev\projects\XXX\node_modules\mochify\lib\mochify.js:132:28)
    at Object.<anonymous> (C:\dev\projects\XXX\node_modules\mochify\bin\cmd.js:27:1)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
```

How I use mochify-istanbul:

```js

"config": {
    "cover_report": "cobertura"
 },
 "scripts": {
    "test:browser": "mochify ./browser/test/*.js",
    "cover": "npm run test:browser -- --plugin [ mochify-istanbul --report $npm_package_config_cover_report --exclude '**/*.mustache' ]"
}

```

**Comment by mantoni** [comment]
@ferlores All our builds are affected now since we depend on `mochify-istanbul@^2.1`.

**Comment by ferlores** [comment]
v2.2.1 was just released, thanks guys

**Comment by mantoni** [comment]
:+1:

**Comment by tjunghans** [comment]
:+1:

**Comment by ferlores** [comment]
Please use v2.2.2 for backward compatibility
